# Generated by Django 4.2.4 on 2023-08-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('img', models.ImageField(upload_to='uploads/% Y/% m/')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
