# Generated by Django 4.1.10 on 2023-08-09 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_competition_cultural_dormitories_game_gym_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultural',
            name='date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='icon',
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titles', models.CharField(max_length=1000, null=True)),
                ('rate', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=500, null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.game')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pdf_title', models.CharField(max_length=1000, null=True)),
                ('pdf_link', models.FileField(null=True, upload_to='')),
                ('attention', models.CharField(max_length=1000, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('coming', models.BooleanField(default=False)),
                ('cities', models.CharField(max_length=2000)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.game')),
            ],
        ),
    ]
