# Generated by Django 4.1.10 on 2023-08-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_cultural_date_remove_game_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='cities',
        ),
        migrations.AddField(
            model_name='competition',
            name='city',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='sex',
            field=models.CharField(choices=[('پسر', 'Boy'), ('دختر', 'Girl')], default='Boy', max_length=20),
        ),
        migrations.AlterField(
            model_name='competition',
            name='attention',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='pdf_link',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='pdf_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
