# Generated by Django 4.1.10 on 2023-08-10 08:45

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_remove_result_full_name_remove_result_titles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
