# Generated by Django 4.1.10 on 2023-08-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_alter_competition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
