# Generated by Django 4.1.10 on 2023-08-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_alter_competition_date_alter_news_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='pdf_link',
            new_name='file_link',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='pdf_title',
            new_name='file_title',
        ),
    ]
