# Generated by Django 4.1.10 on 2023-08-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_survey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'مسابقه', 'verbose_name_plural': 'مسابقه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='cultural',
            options={'verbose_name': 'فرهنگی', 'verbose_name_plural': 'فرهنگی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='dormitories',
            options={'verbose_name': 'خوابگاه', 'verbose_name_plural': 'خوابگاه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'گالری', 'verbose_name_plural': 'گالری'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'بازی', 'verbose_name_plural': 'بازی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='gym',
            options={'verbose_name': 'سالن', 'verbose_name_plural': 'سالن\u200cهای مسابقه\u200c'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'خبر', 'verbose_name_plural': 'اخبار'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'نتیجه', 'verbose_name_plural': 'نتیجه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': 'نظرسنجی', 'verbose_name_plural': 'نظرها'},
        ),
        migrations.AlterField(
            model_name='competition',
            name='attention',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='متن توجه (نوشته قرمز رنگ)'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='city',
            field=models.CharField(default='', max_length=2000, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.CharField(max_length=10, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='file_link',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='file_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='عنوان فایل'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.game', verbose_name='نام بازی'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='cultural',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='cultural',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='cultural',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='dormitories',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='dormitories',
            name='direction_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک گوگل مپ یا بلد'),
        ),
        migrations.AlterField(
            model_name='dormitories',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='dormitories',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام خوابگاه'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام بازی'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='direction_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک گوگل مپ یا بلد'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام سالن'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=10, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='result',
            name='athlete_full_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='نام بازیکن'),
        ),
        migrations.AlterField(
            model_name='result',
            name='attention',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='متن توجه (نوشته قرمز رنگ)'),
        ),
        migrations.AlterField(
            model_name='result',
            name='city',
            field=models.CharField(default='', max_length=1000, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='result',
            name='file_link',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='result',
            name='file_title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='عنوان فایل'),
        ),
        migrations.AlterField(
            model_name='result',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.game', verbose_name='نام بازی'),
        ),
        migrations.AlterField(
            model_name='result',
            name='rate',
            field=models.CharField(default='0', max_length=100, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='context',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
