# Generated by Django 4.1.10 on 2023-08-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0025_alter_competition_options_alter_cultural_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
