# Generated by Django 4.1.10 on 2023-08-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0028_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cultural',
        ),
    ]
