# Generated by Django 4.1.10 on 2023-08-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0030_cultural'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک سایت'),
        ),
    ]
