# Generated by Django 4.1.10 on 2023-08-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0033_topresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topresults',
            name='bronze',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='برنز'),
        ),
        migrations.AlterField(
            model_name='topresults',
            name='gold',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='طلا'),
        ),
        migrations.AlterField(
            model_name='topresults',
            name='silver',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='نقره'),
        ),
    ]
