# Generated by Django 4.1.10 on 2023-09-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0035_remove_topresults_game_id_topresults_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='topresults',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='توضیحات'),
        ),
    ]
