# Generated by Django 4.1.10 on 2023-09-14 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_userprofile_user_alter_userprofile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
