# Generated by Django 4.1.10 on 2023-09-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفابل کاربر', 'verbose_name_plural': 'پروفایل کاربران'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='تصویر پروفایل'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lisense_pics', verbose_name='تصویر کارت یا پروانه'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='noName', max_length=50, verbose_name='نام کاربری'),
        ),
    ]
