# Generated by Django 4.1.10 on 2023-09-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_userprofile_options_userprofile_image_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('option1', 'کاربر عادی'), ('option2', 'مربی'), ('option3', 'سالن\u200cدار')], default='option1', max_length=10, verbose_name='نقش کاربر'),
        ),
    ]
