# Generated by Django 4.1.10 on 2023-09-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/lisense_pics', verbose_name='تصویر کارت یا پروانه'),
        ),
    ]
