# Generated by Django 4.1.10 on 2023-09-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='profile_pics/lisense_pics', verbose_name='تصویر کارت مربی\u200cگری')),
                ('rate', models.IntegerField(blank=True, default=0, null=True, verbose_name='امتیاز')),
                ('education', models.CharField(max_length=40, verbose_name='تحصیلات')),
                ('fields', models.CharField(blank=True, max_length=1000, null=True, verbose_name='تخصص\u200cها')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rate',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('simple_user', 'simple_user'), ('coach', 'coach'), ('gym_manager', 'gym_manager'), ('actor', 'actor')], default='simple_user', max_length=15, verbose_name='نقش کاربر'),
        ),
        migrations.CreateModel(
            name='GymManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام باشگاه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/lisense_pics', verbose_name='تصویر باشگاه')),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='profile_pics/lisense_pics', verbose_name='تصویر پروانه')),
                ('rate', models.IntegerField(blank=True, default=0, null=True, verbose_name='امتیاز')),
                ('location', models.CharField(max_length=1000, verbose_name='آدرس')),
                ('location_link', models.CharField(blank=True, max_length=50, null=True, verbose_name='لینک آدرس')),
                ('possibilities', models.TextField(blank=True, max_length=2000, verbose_name='امکانات')),
                ('coaches', models.ManyToManyField(blank=True, related_name='gyms_managed', to='authentication.coach', verbose_name='مربی\u200cها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=30, verbose_name='رشته')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
    ]
