# Generated by Django 4.1.10 on 2023-09-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_coach_remove_userprofile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.gymmanager', verbose_name='باشگاه'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='رد شده توسط ادمین'),
        ),
    ]
