# Generated by Django 4.1.10 on 2023-09-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_coach_gym_userprofile_accepted_userprofile_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='fields',
            new_name='field',
        ),
        migrations.AddField(
            model_name='actor',
            name='document_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/lisense_pics', verbose_name='تصویر حکم قهرمانی'),
        ),
    ]
