# Generated by Django 4.1.10 on 2023-09-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_rename_fields_coach_field_actor_document_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymmanager',
            name='coaches',
        ),
    ]
