# Generated by Django 4.1.10 on 2023-09-22 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_remove_gymmanager_coaches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='gymmanager',
            name='rate',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
    ]
