# Generated by Django 4.1.10 on 2023-09-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_remove_coach_rate_remove_gymmanager_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='num_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_rating',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=6),
        ),
    ]
