# Generated by Django 4.1.10 on 2023-09-22 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_userprofile_num_ratings_userprofile_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
    ]
