# Generated by Django 4.1.10 on 2023-09-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_userprofile_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentNews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='profile_pics/news', verbose_name='عکس')),
                ('date', models.CharField(max_length=10, verbose_name='تاریخ')),
                ('link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='لینک سایت')),
            ],
            options={
                'verbose_name': 'خبر وزارت ورزش',
                'verbose_name_plural': 'اخبار وزارت ورزش',
            },
        ),
        migrations.AlterField(
            model_name='gymmanager',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/gym_place', verbose_name='تصویر باشگاه'),
        ),
    ]
