# Generated by Django 4.1.10 on 2023-09-24 12:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_departmentnews_alter_gymmanager_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام هیئت')),
                ('goals', models.CharField(blank=True, max_length=1500, null=True, verbose_name='اهداف')),
                ('location', models.CharField(max_length=1000, verbose_name='آدرس')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام اداره')),
                ('location', models.CharField(max_length=1000, verbose_name='آدرس')),
            ],
        ),
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'قهرمان', 'verbose_name_plural': 'قهرمان\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'مربی', 'verbose_name_plural': 'مربی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='gymmanager',
            options={'verbose_name': 'سالن\u200cدار', 'verbose_name_plural': 'سالن\u200cدارها'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(11)], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('simple_user', 'simple_user'), ('coach', 'coach'), ('gym_manager', 'gym_manager'), ('actor', 'actor'), ('office_admin', 'office_admin'), ('office_manager', 'office_manager'), ('office_expert', 'office_expert'), ('board_admin', 'board_admin'), ('board_authorities', 'board_authorities')], default='simple_user', max_length=20, verbose_name='نقش کاربر'),
        ),
        migrations.CreateModel(
            name='OfficeAuthorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.office', verbose_name='اداره')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile', verbose_name='ادمین اداره'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=3000, verbose_name='متن پیام')),
                ('answered', models.BooleanField(default=False, verbose_name='پاسخ\u200cداده شده')),
                ('office_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.officeauthorities', verbose_name='مدیر')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام کلاس')),
                ('date', models.CharField(max_length=10, verbose_name='تاریخ برگزاری')),
                ('time', models.CharField(max_length=8, verbose_name='زمان شروع کلاس')),
                ('location', models.CharField(max_length=100, verbose_name='مکان برگزاری')),
                ('link', models.CharField(max_length=1500, verbose_name='لینک کلاس')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت کلاس')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.board', verbose_name='هیئت برگزارکننده')),
                ('users', models.ManyToManyField(to='authentication.userprofile', verbose_name='افراد شرکت\u200cکننده')),
            ],
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام بازی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='تصویر')),
                ('date', models.CharField(max_length=10, verbose_name='تاریخ برگزاری')),
                ('time', models.CharField(max_length=8, verbose_name='زمان شروع بازی')),
                ('location', models.CharField(max_length=100, verbose_name='مکان برگزاری')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.board', verbose_name='هیئت برگزارکننده')),
            ],
        ),
        migrations.CreateModel(
            name='BoardAuthorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.board', verbose_name='هیئت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile', verbose_name='ادمین هیئت'),
        ),
    ]
