# Generated by Django 4.1.10 on 2023-09-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_board_office_alter_actor_options_alter_coach_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'هیئت', 'verbose_name_plural': 'هیئت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='boardauthorities',
            options={'verbose_name': 'کارشناس اداره', 'verbose_name_plural': 'کارشناس\u200cهای هیئت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='boardgame',
            options={'verbose_name': 'مسابقه هیئت', 'verbose_name_plural': 'مسابقه\u200cهای هیئت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'کلاس', 'verbose_name_plural': 'کلاس\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'اداره', 'verbose_name_plural': 'اداره\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='officeauthorities',
            options={'verbose_name': 'کارمند اداره', 'verbose_name_plural': 'کارمندان اداره\u200cها'},
        ),
        migrations.RenameField(
            model_name='board',
            old_name='goals',
            new_name='goal',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(null=True, unique=True, verbose_name='شماره موبایل'),
        ),
    ]
