# Generated by Django 4.1.10 on 2023-09-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_remove_classroom_users_userprofile_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='classroom',
        ),
        migrations.CreateModel(
            name='JoinedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.classroom', verbose_name='آدرس ایمیل هیئت کلاس')),
                ('user_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.userprofile', verbose_name='آدرس ایمیل کاربر')),
            ],
            options={
                'verbose_name': 'فرد و کلاس',
                'verbose_name_plural': 'افراد و کلاس\u200cها',
            },
        ),
    ]
