# Generated by Django 4.1.10 on 2023-09-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_remove_userprofile_classroom_joinedclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinedclass',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='شماره موبایل'),
        ),
    ]
