# Generated by Django 4.1.10 on 2023-09-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_rename_board_email_joinedclass_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedclass',
            name='father_name',
            field=models.CharField(max_length=30, null=True, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='joinedclass',
            name='full_name',
            field=models.CharField(max_length=30, null=True, verbose_name='نام کاربر'),
        ),
        migrations.AddField(
            model_name='joinedclass',
            name='location',
            field=models.CharField(max_length=30, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='joinedclass',
            name='location_code',
            field=models.CharField(max_length=30, null=True, verbose_name='کدپستی'),
        ),
        migrations.AddField(
            model_name='joinedclass',
            name='national_code',
            field=models.CharField(max_length=30, null=True, verbose_name='کدملی'),
        ),
        migrations.AddField(
            model_name='joinedclass',
            name='passport_number',
            field=models.CharField(max_length=30, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AddField(
            model_name='joinedclass',
            name='phone_number',
            field=models.CharField(max_length=30, null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AddField(
            model_name='joinedclass',
            name='telephone_number',
            field=models.CharField(max_length=30, null=True, verbose_name='شماره ثابت'),
        ),
    ]
