# Generated by Django 4.1.10 on 2023-09-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_joinedclass_father_name_joinedclass_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinedclass',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AddField(
            model_name='joinedclass',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='رد شده'),
        ),
    ]
